---
namespace: prod
microservices:

  api-gateway:
    name: api-gateway
    enabled: true
    image: hagendev/api:latest
    imagePullPolicy:  Always
    tolerations: prod
    hpaCpu: 90
    hpaMemory: 80
    secrets:
      - databases
      - services
    containerPort: 80
    port: 80
    targetPort: 80
    nodePort:
      enabled: true
      externalPort: 32002
    replicas:
      min: 1
      max: 1
    cpu:
      min: 0.1
      max: 0.3
    memory:
      min: 100Mi
      max: 500Mi
    persistentVolume:
      enabled: false

  front:
    name: front
    enabled: true
    image: hagendev/front:latest
    imagePullPolicy:  Always
    tolerations: prod
    hpaCpu: 90
    hpaMemory: 80
    secrets:
      - services
    containerPort: 80
    port: 80
    targetPort: 80
    nodePort:
      enabled: true
      externalPort: 32003
    replicas:
      min: 1
      max: 5
    cpu:
      min: 0.1
      max: 0.4
    memory:
      min: 100Mi
      max: 200Mi
    persistentVolume:
      enabled: false

  back:
    name: back
    enabled: true
    image: hagendev/back:latest
    imagePullPolicy:  Always
    tolerations: prod
    hpaCpu: 90
    hpaMemory: 80
    secrets:
      - databases
      - services
      - aws
    containerPort: 80
    port: 80
    targetPort: 80
    nodePort:
      enabled: true
      externalPort: 32004
    replicas:
      min: 1
      max: 1
    cpu:
      min: 0.1
      max: 0.8
    memory:
      min: 100Mi
      max: 2Gi
    persistentVolume:
      enabled: false

variables:

  configMap:
    services:
      RICK_SANCHEZ: "Wubba Lubba Dub Dub"

  secret:
    services:
      JWT_SECRET_KEY: dWNhbnRhdXRoNjk=
      TOKEN_GITHUB: dWNhbnRhdXRoNjk=

    databases:
      MONGO_USER: aGFnZW4=
      MONGO_PASSWORD: dWNhbnRhdXRoNjk=
      MONGO_DB: aGFnZW4=
      POSTGRES_USER: aGFnZW4=
      POSTGRES_PASSWORD: dWNhbnRhdXRoNjk=
      POSTGRES_DB: aGFnZW4=

    aws:
      AWS_ACCESS_KEY: dWNhbnRhdXRoNjk=
      AWS_SECRET_KEY: dWNhbnRhdXRoNjk=
...
