{{- define "cm" }}
{{- $service := .service }}
{{- $namespace :=  .namespace }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $service.name }}
  namespace: {{ $namespace }}

  # annotations:
  #   "helm.sh/hook": pre-install,pre-upgrade
  #   "helm.sh/hook-weight": "-1"

data:
  {{- range  $key, $value := .variables.configMap.services }}
  {{ $key }}: {{ quote $value }}
  {{- end }}
{{- end }}
{{- end }}

{{- range $service := $.Values.microservices }}
  {{- include "cm" (dict  "service" $service "namespace" $.Values.namespace "variables" $.Values.variables) }}
{{ end }}
