{{- define "secret" }}
{{- $service := .service }}
{{- $namespace := .namespace }}
{{- $variables := .variables }}
{{- $secrets := $service.secrets }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Secret

metadata:
  name: {{ $service.name }}
  namespace: {{ $namespace }}

  # annotations:
  #   "helm.sh/hook": pre-install,pre-upgrade
  #   "helm.sh/hook-weight": "1"

type: Opaque
data:
  {{- range $secretValue := $secrets }}
    {{- range $key, $value := index $variables.secret $secretValue }}
  {{$key}}: {{quote $value}}
    {{- end }}
  {{ end }}


{{- end }}
{{- end }}

{{- range $service :=  $.Values.microservices }}
  {{- include "secret" (dict "service" $service "namespace" $.Values.namespace "variables" $.Values.variables) }}
{{ end }}

{{- range $service :=  $.Values.cronjobs }}
  {{- include "secret" (dict "service" $service "namespace" $.Values.namespace "variables" $.Values.variables) }}
{{- end }}
