namespace: prod
microservices:

  mongodb:
    name: mongodb
    enabled: true
    image: mongo:latest
    imagePullPolicy:  IfNotPresent
    tolerations: database
    hpaCpu: 90
    hpaMemory: 80
    secrets:
      - mongodb
    containerPort: 27017
    port: 27017
    targetPort: 27017
    nodePort:
      enabled: false
      # externalPort: 32000
    replicas:
      min: 1
      max: 1
    cpu:
      min: 0.1
      max: 1.3
    memory:
      min: 300Mi
      max: 2Gi
    persistentVolume:
      enabled: true
      type: local # local or nfs
      # If the NFS type is enabled, it is necessary to inform a server
      # server: 10.0.1.10
      path: /srv/databases/mongodb
      storage: 2Gi
    mountPath: /data/db

variables:

  configMap:
    services:
      RICK_SANCHEZ: "Wubba Lubba Dub Dub"

  secret:
    mongodb:
      MONGO_INITDB_ROOT_USERNAME: aGFnZW4=
      MONGO_INITDB_ROOT_PASSWORD: dWNhbnRhdXRoNjk=
      MONGO_DB_NAME: aGFnZW4=
